name: Update MixChannel HTML

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install chromium

      - run: node scrape.js

      - name: Commit HTML
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add html/events.html

          git diff --cached --quiet || git commit -m "update html"
          git pull --rebase
          git push
