name: Update MixChannel HTML

on:
  workflow_dispatch:

  schedule:
    # 日本時間 0:13 / 8:13 / 16:13
    - cron: "13 15,23,7 * * *"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Show workflow info
        run: |
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Workflow ref: $GITHUB_WORKFLOW_REF"
          echo "Commit: $GITHUB_SHA"
          date -u
          
      - run: npm install

      - run: npx playwright install chromium

      - run: node scrape.js

      - name: Commit events.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add events.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update events.json"
            git pull --rebase
            git push
          fi
